### ISSUE TITLE
mask is none

### ISSUE THREAD

**Issue by Zweiyuan** [fizyr/keras-maskrcnn#67] opened 2019-02-01 00:43 UTC
A part of my "annotations.csv" file is :
> JPEGImages/20130320T004351.039789.Cam6_32.png,,,,,,
JPEGImages/20130320T004351.801805.Cam6_43.png,,,,,,
JPEGImages/20130320T004351.992184.Cam6_61.png,193,105,232,145,apple,masks/20130320T004351.992184.Cam6_61.png
JPEGImages/20130320T004351.992184.Cam6_61.png,131,107,170,147,apple,masks/20130320T004351.992184.Cam6_61.png

And classes file is 

> apple,0

But, when I trained these data, I had a issue.

> Epoch 1/50
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/cbf/anaconda3/envs/tfGPU/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/cbf/anaconda3/envs/tfGPU/lib/python3.6/site-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "keras_maskrcnn/bin/../../keras_maskrcnn/preprocessing/generator.py", line 284, in __getitem__
    inputs, targets = self.compute_input_output(group)
  File "keras_maskrcnn/bin/../../keras_maskrcnn/preprocessing/generator.py", line 256, in compute_input_output
    annotations_group = self.load_annotations_group(group)
  File "keras_maskrcnn/bin/../../keras_maskrcnn/preprocessing/generator.py", line 97, in load_annotations_group
    return [self.load_annotations(image_index) for image_index in group]
  File "keras_maskrcnn/bin/../../keras_maskrcnn/preprocessing/generator.py", line 97, in <listcomp>
    return [self.load_annotations(image_index) for image_index in group]
  File "keras_maskrcnn/bin/../../keras_maskrcnn/preprocessing/csv_generator.py", line 186, in load_annotations
    mask = (mask > 0).astype(np.uint8)  # convert from 0-255 to binary mask
TypeError: '>' not supported between instances of 'NoneType' and 'int'
"""
> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
  File "keras_maskrcnn/bin/train.py", line 325, in <module>
    main()
  File "keras_maskrcnn/bin/train.py", line 321, in main
    max_queue_size=args.max_queue_size
  File "/home/cbf/anaconda3/envs/tfGPU/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/cbf/anaconda3/envs/tfGPU/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/cbf/anaconda3/envs/tfGPU/lib/python3.6/site-packages/keras/engine/training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "/home/cbf/anaconda3/envs/tfGPU/lib/python3.6/site-packages/keras/utils/data_utils.py", line 601, in get
    six.reraise(*sys.exc_info())
  File "/home/cbf/anaconda3/envs/tfGPU/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/cbf/anaconda3/envs/tfGPU/lib/python3.6/site-packages/keras/utils/data_utils.py", line 595, in get
    inputs = self.queue.get(block=True).get()
  File "/home/cbf/anaconda3/envs/tfGPU/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: '>' not supported between instances of 'NoneType' and 'int'

It may be mask is none. I don't know is the issue about data or code.
How can I change?

**Comment by Zweiyuan** [comment] 2019-02-04 10:06
Anyone can help me?

**Comment by hgaiser** [comment] 2019-02-04 10:12
Are you sure the masks exist relative to the CSV file ?

**Comment by Zweiyuan** [comment] 2019-02-04 10:40
@hgaiser I tried to print "masks", and found that it is none.

**Comment by hgaiser** [comment] 2019-03-12 10:46
Did you ever find the cause of your issue ?

**Comment by Zweiyuan** [comment] 2019-03-13 09:27
sorry， I can't solve it. I think it should be missing some files.

**Comment by hgaiser** [comment] 2019-03-13 09:28
> sorry， I can't solve it. I think it should be missing some files.

Yes it sounds like some masks are non-existing.

**Comment by Zweiyuan** [comment] 2019-03-13 09:37
Could you tell me how to get the masks ?
I have images and the bounding boxes, but I have not the masks.

**Comment by hgaiser** [comment] 2019-03-13 09:42
I have no advice on how to create mask annotations, we use our own software for that.

Closing this issue as there is no issue here with our code.

**Closed by hgaiser** 2019-03-13 09:42 UTC

**Comment by Zweiyuan** [comment] 2019-03-13 10:19
thank you. But , could you share your software to me?

**Comment by hgaiser** [comment] 2019-03-13 10:20
Nope, it is privately owned.

**Comment by Wemmy** [comment] 2019-09-11 15:01
I had same problem, but i got my masks. What is the other possible issue?

**Comment by hgaiser** [comment] 2019-09-12 07:13
Double check to make sure that the masks are in the correct location w.r.t. the csv file.
